# Generated by Django 2.2.1 on 2019-06-01 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20190519_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
